# Substation — pipeline single source of truth.
#
# CI/CD for this project is LOCAL and Claude-driven. There is NO cloud CI and
# NO GitHub Actions. `make ci` is the gate; the git pre-push hook (see `make
# hooks`) runs it before every push. Keep it that way.

PY ?= python3
PKG := substation
SRC := substation tests

.DEFAULT_GOAL := help

.PHONY: help dev ci format format-check lint type test schema coverage-build \
        coverage-check security demo demo-cast verify release hooks clean

help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| sort \
		| awk 'BEGIN {FS = ":.*?## "} {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

dev: ## Install the package with dev tooling (pinned)
	$(PY) -m pip install -e ".[dev]"

## ---------------------------------------------------------------------------
## CI — the local gate. Run this after any change; it must pass before "done".
## ---------------------------------------------------------------------------
ci: format-check lint type test schema coverage-build coverage-check security ## Run the full local CI gate
	@echo "--- detection harness (Tier 1 generate->detect->report) runs under 'test'"
	@echo "--- coverage map + Navigator layer regenerated by 'coverage-build', drift-checked by 'coverage-check'"
	@echo "--- security gate (bandit + dep audit + secret scan + SBOM + files-only invariant) ran under 'security'"
	@echo "ci: OK"

format: ## Auto-format the codebase (ruff)
	ruff format $(SRC)

format-check: ## Verify formatting without writing (ruff)
	ruff format --check $(SRC)

lint: ## Lint (ruff)
	ruff check $(SRC)

type: ## Type-check in strict mode (mypy)
	mypy

test: ## Run unit tests (pytest)
	pytest

schema: ## Validate emitted .jsonl events against the frozen event-log JSON Schema
	$(PY) -m substation.schema

coverage-build: ## Generate the ATT&CK-for-ICS coverage map + Navigator layer (from the registry)
	$(PY) -m substation.coverage --out coverage
	$(PY) -m substation.coverage --out docs/coverage   # committed, published snapshot

coverage-check: ## Verify the committed coverage snapshot (docs/coverage) matches the registry
	$(PY) -m substation.coverage --check --out docs/coverage

security: ## Security gate: bandit + dep audit + secret scan + SBOM + files-only invariant
	bandit -q -r $(PKG)
	$(PY) scripts/security/audit_deps.py
	$(PY) scripts/security/secret_scan.py
	$(PY) scripts/security/sbom.py
	pytest -q tests/test_no_raw_socket_send.py tests/test_files_only.py

## ---------------------------------------------------------------------------
## Product targets
## ---------------------------------------------------------------------------
demo: ## Tier-1 one-command demo: generate -> detect -> report (Python-only)
	$(PY) -m substation.cli demo

demo-cast: ## Record `make demo` to an animated SVG/GIF (asciinema + agg; needs a TTY)
	scripts/record-demo.sh

verify: ## Tier-2 validation: real Zeek/ICSNPP fidelity + Zeek/Suricata detections (Docker)
	$(PY) scripts/verify/run.py

release: ## Cut a local release: gate -> build sdist/wheel -> regen artifacts -> bump + changelog -> tag
	$(PY) scripts/release/run.py $(RELEASE_ARGS)

## ---------------------------------------------------------------------------
## Local "continuous" gate
## ---------------------------------------------------------------------------
hooks: ## Install the git pre-push hook that runs `make ci`
	$(PY) scripts/install_hooks.py

clean: ## Remove caches and build artifacts
	rm -rf .mypy_cache .ruff_cache .pytest_cache build dist *.egg-info
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
